apiVersion: v1

kind: Service

metadata:

  name: access-app-service

spec:

  type: NodePort

  selector:

    app: access-app

  ports:

  - protocol: TCP

    port: 80

    targetPort: 80

    nodePort: 30001 # Optional, Minikube will auto-assign a port if not provided




